language: android
sudo:required
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27
licenses: 
  - android-sdk-preview-license-.+ 
  - android-sdk-license-.+ 
  - google-gdk-license-.+ 
before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
   - ./gradlew build connectedCheck
